from __future__ import annotations

from typing import Any, Callable, Dict, List, Optional

import nil_service

class UniqueValue:
	def post(self, data: bytes) -> None: ...


class TaggedValue:
	def post(self, tag: str, data: bytes) -> None: ...


class UniqueFrame:
	def on_load(self, fn: Callable[[], None]) -> None: ...
	def on_sub(self, fn: Callable[[int], None]) -> None: ...
	def add_value(
		self,
		id: str,
		encode_fn: Callable[[], bytes],
		decode_fn: Callable[[bytes], None],
	) -> UniqueValue: ...
	def add_signal(self, id: str, fn: Callable[[], None]) -> None: ...


class TaggedFrame:
	def on_load(self, fn: Callable[[str], None]) -> None: ...
	def on_sub(self, fn: Callable[[str, int], None]) -> None: ...
	def add_value(
		self,
		id: str,
		encode_fn: Callable[[str], bytes],
		decode_fn: Callable[[str, bytes], None],
	) -> TaggedValue: ...
	def add_signal(self, id: str, fn: Callable[[str], None]) -> None: ...


class Core:
	def set_cache_directory(self, path: str) -> None: ...
	def set_groups(self, groups: Dict[str, str]) -> None: ...
	def add_unique_frame(self, id: str, path: Optional[str] = ...) -> UniqueFrame: ...
	def add_tagged_frame(self, id: str, path: Optional[str] = ...) -> TaggedFrame: ...
	def destroy(self) -> None: ...


def create_core(runnable: nil_service.Runnable, event: nil_service.Event) -> Core: ...

def create_core_from_standalone(standalone: nil_service.Standalone) -> Core: ...

def setup_server(web: nil_service.Web, paths: List[str]) -> None: ...


__all__: List[str]
